version: 0.2

phases:
  install:
    commands:
      - echo "Cleaning npm cache and node_modules..."
      - npm cache clean --force # Clear npm cache to avoid corrupted files
      - rm -rf node_modules # Remove existing node_modules to avoid conflicts
      - npm install -g aws-cdk # Install AWS CDK globally
      - npm install # Install project dependencies

  build:
    commands:
      - echo "Running CDK Synth..."
      - cdk synth # Synthesize the CloudFormation template

artifacts:
  files:
    - "**/*"
