version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
      - npm install --save-dev ts-node   # Ensure ts-node is installed
  build:
    commands:
      - cdk synth
      - cdk deploy --require-approval never
artifacts:
  files:
    - '**/*'

