version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Check the Node.js and npm versions
      - node -v
      - npm -v

      # Clean up any existing `cdk` binary in node_modules/.bin
      - rm -f /codebuild/output/src3090643547/src/node_modules/.bin/cdk

      # Install AWS CDK globally
      - npm install -g aws-cdk

      # Install dependencies (including aws-cdk locally)
      - npm install

  pre_build:
    commands:
      # Optional pre-build commands if necessary
      - echo "Pre-build phase completed."

  build:
    commands:
      # Run the CDK synthesis command
      - npx cdk synth

  post_build:
    commands:
      # Optional post-build commands if necessary
      - echo "Build completed."

artifacts:
  files:
    - "**/*" # Upload all files (adjust as necessary)
  discard-paths: yes # Optional: discard paths when uploading

cache:
  paths:
    - "node_modules/**/*" # Cache node_modules to speed up future builds

