version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Check Node.js and npm versions
      - node -v
      - npm -v

      # Clean the npm cache to avoid any potential cache issues
      - npm cache clean --force

      # Remove the existing node_modules directory to avoid conflicts
      - rm -rf /codebuild/output/src3090643547/src/node_modules

      # Remove conflicting binaries like tsc and cdk if they exist
      - rm -f /codebuild/output/src3090643547/src/node_modules/.bin/tsc
      - rm -f /codebuild/output/src3090643547/src/node_modules/.bin/cdk

      # Install AWS CDK globally
      - npm install -g aws-cdk --force

      # Install dependencies locally (including aws-cdk if it's in your package.json)
      - npm install --force

  pre_build:
    commands:
      # Optional pre-build commands if necessary
      - echo "Pre-build phase completed."

  build:
    commands:
      # Run the CDK synthesis command
      - npx cdk synth

  post_build:
    commands:
      # Optional post-build commands if necessary
      - echo "Build completed."

artifacts:
  files:
    - "**/*" # Upload all files (adjust as necessary)
  discard-paths: yes # Optional: discard paths when uploading

cache:
  paths:
    - "node_modules/**/*" # Cache node_modules to speed up future builds
