version: 0.2
phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
      - npm install --save-dev ts-node # Explicitly install ts-node
  build:
    commands:
      - npx cdk synth # Using `npx` to ensure the correct executable is used
      - npx cdk deploy --require-approval never # Using `npx` here as well
artifacts:
  files:
    - "**/*"
