version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # You can adjust this based on the Node.js version you need
    commands:
      # Check the Node.js and npm versions
      - node -v
      - npm -v

      # Install AWS CDK globally and locally
      - npm install -g aws-cdk
      - npm install aws-cdk --save-dev

      # Install all dependencies
      - npm install

  pre_build:
    commands:
      # You can add any pre-build commands here (e.g., environment setup)
      - echo "Pre-build phase completed."

  build:
    commands:
      # Run the CDK synthesis command
      - npx cdk synth

  post_build:
    commands:
      # Any post-build tasks you might have
      - echo "Build completed."

artifacts:
  files:
    - "**/*" # Upload all files (adjust as necessary)
  discard-paths: yes # Optional: discard paths when uploading

cache:
  paths:
    - "node_modules/**/*" # Cache node_modules to speed up future builds

